/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.kafka:kafka-streams:2.7.0")
    implementation("org.apache.lucene:lucene-core:9.4.1")
    testImplementation("org.apache.lucene:lucene-queryparser:9.4.1")

    testImplementation("org.assertj:assertj-core:3.23.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")

    testImplementation("org.testcontainers:testcontainers:1.17.5")
    testImplementation("org.testcontainers:junit-jupiter:1.17.5")
    testImplementation("org.testcontainers:redpanda:1.17.5")
    testImplementation("com.fasterxml.jackson.core:jackson-core:2.13.4")
    testImplementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4")
}

application {
    mainClass.set("cz.chrismati.blog_projects.lucene_store.App")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
